---
version: '3.1'

services:

  redmine-one:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db-one
      REDMINE_DB_PASSWORD: changeit

  redmine-two:
    image: redmine
    restart: always
    ports:
      - 8082:3000
    environment:
      REDMINE_DB_MYSQL: db-two
      REDMINE_DB_PASSWORD: changeit


  db-one:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeit
      MYSQL_DATABASE: redmine

  db-two:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeit
      MYSQL_DATABASE: redmine
